module.exports = {
  BTC: "bitcoin",
  ETH: "ethereum",
  BNB: "binancecoin",
  SOL: "solana",
  XRP: "ripple",
  ADA: "cardano",
  DOGE: "dogecoin",
  DOT: "polkadot",
  AVAX: "avalanche-2",
  MATIC: "matic-network",
  LTC: "litecoin",
  TRX: "tron",
  LINK: "chainlink",
  XLM: "stellar",
  ATOM: "cosmos",
  ETC: "ethereum-classic",
  XMR: "monero",
  BCH: "bitcoin-cash",
};
